# Generated by Django 4.1 on 2023-04-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predict", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
