# Generated by Django 4.1 on 2023-04-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predict", "0002_alter_node_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="action",
            field=models.CharField(default="Buy", max_length=10),
        ),
    ]
